org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

maven_group=dev.limucc
archives_base_name=block-unrenderer
mod_version=1.3.0

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
fabric_api_version=0.154.2+26.2

modmenu_version=20.0.0
mixinextras_version=0.5.4
minotaur_version=2.+
modrinth_project_id=9fQJdnIj
